### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by nelsonblaha** [opennomad/todo.txt-later#1]
Any tips on sorting later.txt by priority? Are there todo.txt CLI tools that can reach later.txt besides 'mv' that I'm not aware of? Thanks

**Comment by opennomad** [comment]
@nelsonblaha I've moved away from todo.txt, but I believe if you're on a box that has the `sort` command you can use something like this: `sort -t' ' -k2 later.txt`, Bascially it sorts based on the 2nd field, where fields are delimited by whitespace. It's likely not perfect, but should be close.

**Comment by nelsonblaha** [comment]
Thanks!
